### ISSUE TITLE
usage of importlib_metadata for python 3.9 apears to harm zipapps

### ISSUE THREAD

**Issue by franzhaas** [python/importlib_metadata#388] opened 2022-06-19 08:43 UTC
See also.:

https://github.com/streamlit/streamlit/pull/4875

can it be that importlib_metadata is incompatible with zipapps?

Thanks for clarification,
Franz

**Comment by jaraco** [comment] 2022-06-23 18:23
Can you please elaborate? What is happening? What do you expect instead? Can you describe the problem in a way that I could reproduce it (minimally, ideally)? Can you describe what a zipapp is and what is different about it that might be implicated?

This package does support loading metadata from zip archives found on sys.path via the `MetadataPathFinder`. It also provides extensibility such that custom finders can implement `find_distributions` to allow metadata to be supplied even when not using the built-in finders. It may be that whatever is producing these zipapps needs to supply more behavior to enable metadata to be discoverable, though it does sound as if the issue may be related to something else if `importlib.metadata` is working as expected.

**Comment by jaraco** [comment] 2022-10-01 16:59
This project has done all it can to support zipapps. If the zipapps maintainer(s) wish to reach out for advice on how importlib metadata can support their use case, I'm happy to help. In the meantime, since this issue is languishing, I'm closing it as invalid.

**Closed by jaraco** 2022-10-01 16:59 UTC
