### ISSUE TITLE
`importlib_metadata.metadata("")` start raising ValueError since 4.12.0

### ISSUE THREAD

**Issue by Czaki** [python/importlib_metadata#395] opened 2022-07-04 07:44 UTC
Hello,

In `napari` we use the following code to check the metadata of the package used as a launcher of the application: 

```
app_module = sys.modules['__main__'].__package__
try:
    metadata = importlib_metadata.metadata(app_module)
except importlib_metadata.PackageNotFoundError:
    ...
```

as `importlib_metadata` is replacement for `importlib.metadata` then there is inconsitece as for python 3.8-3.10 the following code executes correctly:

```
In [2]: importlib.metadata.metadata(None)
Out[2]: <email.message.Message at 0x7fdb7c5ff5e0>
```

but 
```
importlib_metadata.metadata(None)
```

ends with error from https://github.com/python/importlib_metadata/pull/391

I found this issue, but as I understand that solution will impact python 3.11 or python 3.12 

https://github.com/python/cpython/issues/93259

it is possible to restore old behaviour for old version of python to not break existing code? I understand that new version of libraries should be fixed, but such updates should not break existing code.

**Comment by jaraco** [comment] 2022-07-29 16:18
The fact that `metadata("")` or `metadata(None)` did not raise an error was a bug and probably didn't do what you intended it to do. It was unexpected that users would rely on this behavior, which is why it was released as a minor release and not a major (breaking) release. I'd suggest to pin to `importlib_metadata<4.12` in affected environments to work around the issue.

Because it was a backward-incompatible change introduced in a point release, it's conceivable that we should roll back the change, and then re-apply the change in a major release (5.0), but I suspect that wouldn't help your situation. Would that help any more than for you to pin to <4.12?

> it is possible to restore old behaviour for old version of python to not break existing code?

`importlib_metadata` attempts to provide a uniform implementation across all versions of Python and does not wish to provide divergent implementations based on Python versions.

**Comment by Czaki** [comment] 2022-07-29 16:48
The core problem for us is that it affects the already released version that is available on pypi. New releases are working, but in science, it sometimes needs to install old releases for reproducibility. But if you think that such change is wrong we will try to put proper information in documentation.

**Comment by jaraco** [comment] 2022-07-29 23:53
> New releases are working, but in science, it sometimes needs to install old releases for reproducibility.

I understand reproducibility is important. In that case, the best thing to do to maintain reproducibility and compatibility is not to update importlib_resources (keep the pin to `<4.12`).

> But if you think that such change is wrong we will try to put proper information in documentation.

Indeed, I don't see a way short of restoring the prior behavior and re-introducing the bug. I'm not sure what documentation you speak of, but yes, I'd recommend to link to this issue to inform any users affected. Thanks.

**Closed by jaraco** 2022-07-29 23:53 UTC
